[package]
name = "fastbloom-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6.3"
siphasher = "0.3.10"
fastmurmur3 = "0.1.2"
smallvec = "1.8.0"