name: Test Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  CONDA_PREFIX: /usr/share/miniconda

jobs:
  test:
    name: Build and test python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ x86_64, aarch64, ppc64le, ppc64, i686, armv7, armv7l, s390x ]
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
          echo $CONDA
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r build.requirements.txt
      - name: Maturin develop
        uses: PyO3/maturin-action@v1
        with:
          maturin-version: latest
          target: ${{ matrix.target }}
          command: develop
          args: --release
      - name: python unittest
        run: pytest py_tests
