name: Test Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Rust unittest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ x86_64, aarch64, ppc64le, ppc64, i686, armv7, armv7l, s390x ]
    steps:
      - uses: actions/checkout@v3
      - name: maturin build
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_PASS }}
        with:
          rust-toolchain: stable
          target: ${{ matrix.target }}
          command: build
          args: --release
      - name: Run tests
        env:
          RUST_TARGET: ${{ matrix.target }}
        run: |
          echo 'rust target ${RUST_TARGET}'
          cargo test --target $RUST_TARGET --package fastbloom-rs --all-targets